name: subscriptionalertapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State Managment
  mobx: ^2.0.7+3

  #MobX's Widgets
  flutter_mobx: ^2.0.6+1

  #Mobx's annotations
  mobx_codegen: ^2.0.7

  #Json Converter
  json_serializable: ^6.2.0

  #Json Annotations
  json_annotation: ^4.5.0

  #Dependecy Injection 
  get_it: ^7.2.0

  #Dependency Injection Annotations
  injectable: ^1.5.3

  #Navigator
  go_router: ^4.1.0

  #Localization
  easy_localization: ^3.0.1

  #Device Capabilities
  flutter_screenutil: ^5.5.3+2

  #Network
  #dio: ^4.0.6

  #Database
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  #Random id 
  uuid: ^3.0.6

  #Path provider
  #path_provider: ^2.0.11

  #Theme
  flex_color_scheme: ^5.0.1
  #cupertino_icons: ^1.0.2

  #Internet Connection
  #connectivity_plus: ^2.3.5

  #Animation
  animations: ^2.0.3

  #Local Notifications
  flutter_local_notifications: ^9.6.1

  #Listen Local Notifications
  rxdart: ^0.27.4

  #Timezone for Local Notifications
  timezone: ^0.8.0

  #Date Time Picker
  date_time_picker: ^2.1.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Generators
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.3

  #Lints
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
  #Localization assets
    - assets/translations/

scripts:
  build_runner_delete: flutter pub run build_runner build --delete-conflicting-outputs
  build_runner_watch: flutter pub run build_runner build